import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BlogItem from "../components/BlogItem";
import PageTitle from "../components/PageTitle";
import ProductItem from "../components/ProductItem";
import { IBlogs, IProduct } from "../types";

interface Props {
  products: IProduct[];
  blogs: IBlogs[];
}

const Search: NextPage<Props> = ({ products, blogs }) => {
  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={"Search"} />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          {/* blogs  */}
          <>
            <h2 className="mb-5">Blogs</h2>
            <div className="row isotope-grid">
              {/* blog skeleton - search result */}
              {blogs.map((blog) => (
                <div className="col-4" key={blog.id}>
                  <BlogItem blogs={blog} />
                </div>
              ))}

              {/* !! */}
            </div>
          </>

          {/* products */}
          <>
            <h2 className="mb-5">Products</h2>
            <div className="row isotope-grid">
              {/* product skeleton */}
              {products.map((product) => (
                <div className="col-4" key={product.id}>
                  <ProductItem product={product} />
                </div>
              ))}
              {/* !! */}
            </div>
          </>
        </div>
      </div>
    </>
  );
};

export default Search;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const searchQuery = query.search || "";

  const [blogsRes, productsRes] = await Promise.all([
    fetch(`http://localhost:5001/blogs?q=${searchQuery}`),
    fetch(`http://localhost:5001/products?q=${searchQuery}`),
  ]);

  const [blogs, products] = await Promise.all([
    blogsRes.json(),
    productsRes.json(),
  ]);

  return {
    props: {
      blogs,
      products,
    },
  };
};
